# Generated by Django 2.0.5 on 2018-10-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_turnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenprog',
            name='fecha_programa',
            field=models.DateTimeField(blank=True),
        ),
    ]
