# Generated by Django 2.0.5 on 2018-10-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20181013_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenprog',
            name='fecha_programa',
            field=models.CharField(default='vacio', max_length=200),
        ),
    ]
