# Generated by Django 2.0.5 on 2018-10-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20181013_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenprog',
            name='fecha_programa',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ordenprog',
            name='horizontefin',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordenprog',
            name='horizonteini',
            field=models.DateTimeField(blank=True),
        ),
    ]
