# Generated by Django 2.0.5 on 2018-10-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20181013_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprog',
            name='datefinajustada',
            field=models.DateTimeField(),
        ),
    ]
