# Generated by Django 2.0.5 on 2018-10-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20181013_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaproducciones',
            name='completo_unidades',
            field=models.CharField(default='vacio', max_length=200),
        ),
    ]
