# Generated by Django 2.0.5 on 2018-10-13 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_cargaproducciones_completo_unidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodreal',
            name='cargamasiva',
        ),
        migrations.DeleteModel(
            name='CargaProducciones',
        ),
    ]
