# Generated by Django 2.0.5 on 2018-10-13 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20181013_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaProducciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateTimeField(default=datetime.datetime.now)),
                ('completo_unidades', models.CharField(default='vacio', max_length=200)),
            ],
        ),
    ]
