# Generated by Django 2.0.5 on 2018-10-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_prodreal_cargamasiva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodreal',
            name='cargamasiva',
        ),
        migrations.DeleteModel(
            name='CargaProducciones',
        ),
    ]
