# Generated by Django 2.0.5 on 2018-10-13 21:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_cargaproducciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodreal',
            name='cargamasiva',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='fecha_carga_producciones', to='blog.CargaProducciones'),
            preserve_default=False,
        ),
    ]
