# Generated by Django 2.0.5 on 2018-10-13 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_prodreal_cargamasiva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodreal',
            old_name='cargamasiva',
            new_name='cargamasivaa',
        ),
    ]
