# Generated by Django 2.0.5 on 2018-10-13 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_auto_20181013_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodreal',
            name='cargamasivaa',
        ),
    ]
