# Generated by Django 2.0.5 on 2018-10-13 21:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('Patient', models.CharField(blank=True, max_length=200, null=True)),
                ('Date', models.CharField(blank=True, max_length=200, null=True)),
                ('Time', models.CharField(blank=True, max_length=200, null=True)),
                ('Duration', models.CharField(blank=True, max_length=200, null=True)),
                ('Location', models.CharField(blank=True, max_length=200, null=True)),
                ('Clinician', models.CharField(blank=True, max_length=200, null=True)),
                ('AppointmentType', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isbn_number', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='CargaCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CargaProducciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateTimeField(default=datetime.datetime.now)),
                ('completo_unidades', models.CharField(default='vacio', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleProg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workcenter', models.CharField(default='vacio', max_length=200)),
                ('orderId', models.CharField(default='vacio', max_length=200)),
                ('dateini', models.CharField(default='vacio', max_length=200)),
                ('datefin', models.CharField(default='vacio', max_length=200)),
                ('datefinajustada', models.DateTimeField()),
                ('turno', models.CharField(default='vacio', max_length=200)),
                ('qIn', models.CharField(default='vacio', max_length=200)),
                ('orderIdPrev', models.CharField(default='vacio', max_length=200)),
                ('orderIdPost', models.CharField(default='vacio', max_length=200)),
                ('completo_fechaturno', models.CharField(default='vacio', max_length=200)),
                ('completo_secuencia', models.CharField(default='vacio', max_length=200)),
                ('completo_unidades', models.CharField(default='vacio', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquina', models.CharField(default='vacio', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OCImportacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oc', models.CharField(max_length=200)),
                ('proveedor', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mes_arribo_esperado', models.CharField(choices=[('Enero', 'January'), ('Febrero', 'February'), ('Marzo', 'March'), ('Abril', 'April')], max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenConv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('maquina', models.CharField(max_length=200)),
                ('fechainiprog', models.CharField(max_length=200)),
                ('fechafinprog', models.CharField(max_length=200)),
                ('unisprog', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programa', models.DateTimeField()),
                ('transaction_index', models.CharField(default='vacio', max_length=200)),
                ('horizonteini', models.DateTimeField(blank=True)),
                ('horizontefin', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProdID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='orden', max_length=200)),
                ('transactindex', models.CharField(max_length=200)),
                ('plantid', models.CharField(blank=True, max_length=200, null=True)),
                ('workcenter', models.CharField(blank=True, max_length=200, null=True)),
                ('orderid', models.CharField(blank=True, max_length=200, null=True)),
                ('setupstartdate', models.CharField(blank=True, max_length=200, null=True)),
                ('setupenddate', models.CharField(blank=True, max_length=200, null=True)),
                ('runstartdate', models.CharField(blank=True, max_length=200, null=True)),
                ('runenddate', models.CharField(blank=True, max_length=200, null=True)),
                ('duracion', models.CharField(blank=True, max_length=200, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('Patient', models.CharField(blank=True, max_length=200, null=True)),
                ('Date', models.CharField(blank=True, max_length=200, null=True)),
                ('Time', models.CharField(blank=True, max_length=200, null=True)),
                ('Location', models.CharField(blank=True, max_length=200, null=True)),
                ('Clinician', models.CharField(blank=True, max_length=200, null=True)),
                ('AppointmentType', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdReal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(default='vacio', max_length=200)),
                ('orderId', models.CharField(default='vacio', max_length=200)),
                ('padron', models.CharField(default='vacio', max_length=200)),
                ('datefin', models.CharField(default='vacio', max_length=200)),
                ('datefinajustada', models.CharField(default='vacio', max_length=200)),
                ('turno', models.CharField(default='vacio', max_length=200)),
                ('qOrd', models.CharField(default='vacio', max_length=200)),
                ('lamDisp', models.CharField(default='vacio', max_length=200)),
                ('nSalidas', models.CharField(default='vacio', max_length=200)),
                ('qProd', models.CharField(default='vacio', max_length=200)),
                ('porcTerm', models.CharField(default='vacio', max_length=200)),
                ('maquina', models.CharField(default='vacio', max_length=200)),
                ('orderIdPrev', models.CharField(default='vacio', max_length=200)),
                ('orderIdPost', models.CharField(default='vacio', max_length=200)),
                ('cargamasivaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fecha_carga_producciones', to='blog.CargaProducciones')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaConv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PruebaMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato1', models.CharField(default='vacio', max_length=200)),
                ('dato2', models.CharField(default='vacio', max_length=200)),
                ('ultrafile', models.TextField(default='hola,que,tal')),
            ],
        ),
        migrations.CreateModel(
            name='PruebaTabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(default='vacio', max_length=200)),
                ('item2', models.CharField(default='vacio', max_length=200)),
                ('item3', models.TextField(default='vacio', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SolCamb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='holi', max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('solicitudot', models.CharField(max_length=200)),
                ('order_id', models.CharField(max_length=200)),
                ('cliente', models.CharField(max_length=200)),
                ('fechabpt', models.CharField(max_length=200)),
                ('maquina', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('approved_cambio', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(default='vacio', max_length=10)),
                ('horaini', models.CharField(default='vacio', max_length=100)),
                ('horafin', models.CharField(default='vacio', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ordenconv',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenconvs', to='blog.ProgramaConv'),
        ),
        migrations.AddField(
            model_name='detalleprog',
            name='programma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fecha_prog', to='blog.OrdenProg'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='blog.Book'),
        ),
    ]
