# Generated by Django 2.0.5 on 2018-10-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181015_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodreal',
            name='datefin',
            field=models.DateTimeField(),
        ),
    ]
