# Generated by Django 2.0.5 on 2018-10-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181015_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(default='vacio', max_length=20)),
                ('texto', models.TextField(default='Minuta:')),
                ('integrantes', models.CharField(default='vacio', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='pruebamod',
            name='ultrafile',
            field=models.TextField(default=''),
        ),
    ]
