# Generated by Django 2.0.5 on 2018-10-17 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20181016_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(default='.', editable=False, max_length=100, unique=True)),
                ('padron', models.CharField(default='.', max_length=100)),
                ('cliente', models.CharField(default='.', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 10, 16, 22, 51, 3, 850196)),
        ),
    ]
