# Generated by Django 2.0.5 on 2018-10-27 23:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20181027_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaconv',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Maquinas'),
        ),
        migrations.AlterField(
            model_name='diaconv',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Turnos'),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 10, 27, 20, 7, 43, 786817)),
        ),
    ]
