# Generated by Django 2.0.5 on 2018-11-04 01:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20181103_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaConv2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaajust', models.DateField(default=datetime.datetime(2018, 11, 3, 0, 0))),
                ('compIdFFG', models.FloatField(default=0)),
                ('compM2FFG', models.FloatField(default=0)),
                ('compIdFFW', models.FloatField(default=0)),
                ('compM2FFW', models.FloatField(default=0)),
                ('compIdTCY', models.FloatField(default=0)),
                ('compM2TCY', models.FloatField(default=0)),
                ('compIdHCR', models.FloatField(default=0)),
                ('compM2HCR', models.FloatField(default=0)),
                ('compIdWRD', models.FloatField(default=0)),
                ('compM2WRD', models.FloatField(default=0)),
                ('compIdDRO', models.FloatField(default=0)),
                ('compM2DRO', models.FloatField(default=0)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Turnos')),
            ],
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 11, 3, 22, 46, 45, 29173)),
        ),
    ]
