# Generated by Django 2.0.5 on 2018-11-17 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20181117_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 11, 17, 14, 9, 42, 592108)),
        ),
    ]
