# Generated by Django 2.0.5 on 2018-11-17 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20181117_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meses',
            name='año',
            field=models.CharField(default='vacio', max_length=10),
        ),
        migrations.AlterField(
            model_name='meses',
            name='dias',
            field=models.CharField(default='vacio', max_length=10),
        ),
        migrations.AlterField(
            model_name='meses',
            name='diasnoprod',
            field=models.CharField(default='vacio', max_length=10),
        ),
        migrations.AlterField(
            model_name='meses',
            name='mes',
            field=models.CharField(default='vacio', max_length=10),
        ),
        migrations.AlterField(
            model_name='meses',
            name='mescorto',
            field=models.CharField(default='vacio', max_length=10),
        ),
        migrations.AlterField(
            model_name='meses',
            name='mesnum',
            field=models.CharField(default='vacio', max_length=10),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 11, 17, 18, 16, 27, 702442)),
        ),
    ]
