# Generated by Django 2.0.5 on 2018-11-26 03:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_auto_20181125_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodreal',
            name='anno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prodreal',
            name='mes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prodreal',
            name='semana',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2018, 11, 26, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 11, 26, 3, 46, 36, 788547, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2018, 11, 26, 0, 0, tzinfo=utc)),
        ),
    ]
