# Generated by Django 2.0.5 on 2018-11-27 00:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20181126_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2018, 11, 27, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='meses',
            name='año',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meses',
            name='mesnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 11, 27, 0, 45, 42, 333000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordenprogcorr',
            name='fecha_programa',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2018, 11, 27, 0, 0, tzinfo=utc)),
        ),
    ]
