# Generated by Django 2.0.5 on 2019-01-06 00:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_auto_20181210_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdRealCorrr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajustedatefin', models.CharField(default='vacio', max_length=40)),
                ('ajuste', models.CharField(default='vacio', max_length=20)),
                ('onda', models.CharField(default='vacio', max_length=20)),
                ('formato', models.CharField(default='vacio', max_length=20)),
                ('carton', models.CharField(default='vacio', max_length=20)),
                ('metroslineales', models.IntegerField(default=0)),
                ('trim', models.IntegerField(default=0)),
                ('datefin', models.DateTimeField()),
                ('datefinajustada', models.DateTimeField()),
                ('turno', models.CharField(default='vacio', max_length=10)),
                ('duración_min', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2019, 1, 6, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2019, 1, 6, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 1, 6, 0, 1, 34, 795096, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2019, 1, 6, 0, 0, tzinfo=utc)),
        ),
    ]
