# Generated by Django 2.0.5 on 2019-01-20 22:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0055_auto_20190105_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyMkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaproy', models.DateField(default=datetime.datetime(2019, 1, 20, 0, 0, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='ProyMktMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(default='vacio', max_length=10)),
                ('mescorto', models.CharField(default='vacio', max_length=10)),
                ('mesnum', models.IntegerField(default=0)),
                ('tot_unidades', models.IntegerField(default=1)),
                ('tot_me', models.IntegerField(default=1)),
                ('tot_golpes', models.IntegerField(default=1)),
                ('proymkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proymkt', to='blog.ProyMkt')),
            ],
        ),
        migrations.CreateModel(
            name='ProyMktPadron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(default='vacio', max_length=20)),
                ('padron', models.CharField(default='vacio', max_length=20)),
                ('descripcion', models.CharField(default='vacio', max_length=100)),
                ('mercado', models.CharField(default='vacio', max_length=10)),
                ('maquina', models.CharField(default='vacio', max_length=10)),
                ('carton', models.CharField(default='vacio', max_length=10)),
                ('unidades', models.IntegerField(default=0)),
                ('m2', models.IntegerField(default=0)),
                ('tons', models.IntegerField(default=0)),
                ('ton_placa_equiv', models.IntegerField(default=0)),
                ('proymktmes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proymktmes', to='blog.ProyMktMes')),
            ],
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2019, 1, 20, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2019, 1, 20, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 1, 20, 22, 46, 52, 184403, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2019, 1, 20, 0, 0, tzinfo=utc)),
        ),
    ]
