# Generated by Django 2.0.5 on 2019-02-04 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0057_auto_20190204_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 2, 4, 15, 18, 36, 945389, tzinfo=utc)),
        ),
    ]
