# Generated by Django 2.0.5 on 2019-02-10 15:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0058_auto_20190204_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprog',
            name='anchoplaca',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detalleprog',
            name='largoplaca',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detalleprog',
            name='numberout',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2019, 2, 10, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2019, 2, 10, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 2, 10, 15, 48, 54, 452471, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2019, 2, 10, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proymkt',
            name='fechaproy',
            field=models.DateField(default=datetime.datetime(2019, 2, 10, 0, 0, tzinfo=utc)),
        ),
    ]
