# Generated by Django 2.0.13 on 2019-05-13 01:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0061_auto_20190512_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infowip',
            name='fechamuestra',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 1, 36, 17, 137093, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 5, 13, 1, 36, 17, 147093, tzinfo=utc)),
        ),
    ]
