# Generated by Django 2.2.2 on 2019-06-28 04:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0065_auto_20190628_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infowip',
            name='fechamuestra',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 4, 48, 46, 215279, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 6, 28, 4, 48, 46, 220507, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='SolCamb',
        ),
    ]
