# Generated by Django 2.2.2 on 2019-07-02 02:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0077_auto_20190702_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infowip',
            name='fechamuestra',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 2, 2, 48, 56, 239367, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 7, 2, 2, 48, 56, 244637, tzinfo=utc)),
        ),
    ]
