# Generated by Django 2.2.2 on 2019-07-02 04:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0083_auto_20190702_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='Rut',
            field=models.CharField(default='vacio', max_length=15),
        ),
        migrations.AddField(
            model_name='camion',
            name='Telefono',
            field=models.CharField(default='vacio', max_length=15),
        ),
        migrations.AlterField(
            model_name='camion',
            name='Chofer',
            field=models.CharField(default='vacio', max_length=15),
        ),
        migrations.AlterField(
            model_name='camion',
            name='Transportista',
            field=models.CharField(default='vacio', max_length=20),
        ),
        migrations.AlterField(
            model_name='infowip',
            name='fechamuestra',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 2, 4, 18, 56, 962206, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 7, 2, 4, 18, 56, 967437, tzinfo=utc)),
        ),
    ]
