# Generated by Django 2.2.2 on 2019-07-15 04:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0086_auto_20190709_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCorrplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.CharField(default='vacio', max_length=15)),
                ('fecha_inicio', models.CharField(default='vacio', max_length=15)),
                ('order_id', models.CharField(default='vacio', max_length=15)),
                ('cliente', models.CharField(default='vacio', max_length=15)),
                ('SO', models.CharField(default='vacio', max_length=15)),
                ('carton', models.CharField(default='vacio', max_length=15)),
                ('padron', models.CharField(default='vacio', max_length=15)),
                ('cant_ord', models.CharField(default='vacio', max_length=15)),
                ('cant_corr', models.CharField(default='vacio', max_length=15)),
                ('medida', models.CharField(default='vacio', max_length=15)),
                ('area', models.CharField(default='vacio', max_length=15)),
                ('ruta', models.CharField(default='vacio', max_length=25)),
                ('estado', models.CharField(default='vacio', max_length=15)),
                ('comprometida', models.CharField(default='vacio', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='camion',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 7, 15, 4, 54, 10, 781047, tzinfo=utc), max_length=10),
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2019, 7, 15, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2019, 7, 15, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='infowip',
            name='fechamuestra',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 4, 54, 10, 781599, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 7, 15, 4, 54, 10, 786420, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2019, 7, 15, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proymkt',
            name='fechaproy',
            field=models.DateField(default=datetime.datetime(2019, 7, 15, 0, 0, tzinfo=utc)),
        ),
    ]
