# Generated by Django 2.2.2 on 2019-07-16 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0088_auto_20190715_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoCorrplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_foto', models.DateTimeField(default=datetime.datetime(2019, 7, 16, 14, 51, 57, 786988, tzinfo=utc), unique=True)),
                ('usuario_foto', models.CharField(default='vacio', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='camion',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 7, 16, 14, 51, 57, 788757, tzinfo=utc), max_length=10),
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2019, 7, 16, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2019, 7, 16, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='infowip',
            name='fechamuestra',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 16, 14, 51, 57, 789284, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 7, 16, 14, 51, 57, 793930, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2019, 7, 16, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proymkt',
            name='fechaproy',
            field=models.DateField(default=datetime.datetime(2019, 7, 16, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='ordencorrplan',
            name='programa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='foto_corrplan', to='blog.FotoCorrplan'),
        ),
    ]
