# Generated by Django 2.2.2 on 2019-07-21 16:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0095_auto_20190721_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 7, 21, 16, 58, 56, 562708, tzinfo=utc), max_length=10),
        ),
        migrations.AlterField(
            model_name='fotocorrplan',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 16, 58, 56, 560933, tzinfo=utc), unique=True),
        ),
        migrations.AlterField(
            model_name='infowip',
            name='fechamuestra',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 16, 58, 56, 563267, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 7, 21, 16, 58, 56, 568045, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 16, 58, 56, 561272, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 16, 58, 56, 561294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='maquina',
            field=models.ForeignKey(default='vacio', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='maquina_programada', to='blog.Maquinas'),
        ),
    ]
