# Generated by Django 2.2.2 on 2019-07-21 17:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0096_auto_20190721_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 7, 21, 17, 2, 17, 887310, tzinfo=utc), max_length=10),
        ),
        migrations.AlterField(
            model_name='fotocorrplan',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 17, 2, 17, 885523, tzinfo=utc), unique=True),
        ),
        migrations.AlterField(
            model_name='infowip',
            name='fechamuestra',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 17, 2, 17, 887855, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 7, 21, 17, 2, 17, 892810, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 17, 2, 17, 885866, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 17, 2, 17, 885889, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='maquina',
            field=models.ForeignKey(default='vacio', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='maquina_prog', to='blog.Maquinas'),
        ),
    ]
