# Generated by Django 2.2.2 on 2019-07-21 18:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0097_auto_20190721_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 7, 21, 18, 45, 57, 438901, tzinfo=utc), max_length=10),
        ),
        migrations.AlterField(
            model_name='fotocorrplan',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 18, 45, 57, 437067, tzinfo=utc), unique=True),
        ),
        migrations.AlterField(
            model_name='infowip',
            name='fechamuestra',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 18, 45, 57, 439433, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 7, 21, 18, 45, 57, 444079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 18, 45, 57, 437418, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 18, 45, 57, 437441, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='maquina',
            field=models.ForeignKey(default='vacio', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='maquina_programada', to='blog.Maquinas'),
        ),
    ]
