# Generated by Django 2.2.2 on 2019-07-24 00:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0100_auto_20190722_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalleBPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(default='vacio', max_length=7)),
                ('sector', models.CharField(default='vacio', max_length=7)),
                ('npallets', models.IntegerField(default=0)),
                ('m2', models.FloatField(default=0)),
                ('tons', models.FloatField(default=0)),
                ('maxm2', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='camion',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 7, 24, 0, 10, 21, 434912, tzinfo=utc), max_length=10),
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2019, 7, 24, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fotocorrplan',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 0, 10, 21, 433732, tzinfo=utc), unique=True),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2019, 7, 24, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='infowip',
            name='fechamuestra',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 0, 10, 21, 435431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 7, 24, 0, 10, 21, 440274, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 0, 10, 21, 434081, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 0, 10, 21, 434103, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2019, 7, 24, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proymkt',
            name='fechaproy',
            field=models.DateField(default=datetime.datetime(2019, 7, 24, 0, 0, tzinfo=utc)),
        ),
    ]
