# Generated by Django 2.2.2 on 2019-07-29 02:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0101_auto_20190724_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='Chofer',
            field=models.CharField(default='vacio', max_length=25),
        ),
        migrations.AlterField(
            model_name='camion',
            name='Transportista',
            field=models.CharField(default='vacio', max_length=25),
        ),
        migrations.AlterField(
            model_name='camion',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 7, 29, 2, 36, 50, 216486, tzinfo=utc), max_length=10),
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2019, 7, 29, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fotocorrplan',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 2, 36, 50, 214755, tzinfo=utc), unique=True),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2019, 7, 29, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='infowip',
            name='fechamuestra',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 2, 36, 50, 217044, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 7, 29, 2, 36, 50, 221834, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 2, 36, 50, 215084, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 2, 36, 50, 215106, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2019, 7, 29, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proymkt',
            name='fechaproy',
            field=models.DateField(default=datetime.datetime(2019, 7, 29, 0, 0, tzinfo=utc)),
        ),
    ]
