# Generated by Django 2.0.13 on 2019-08-29 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0108_auto_20190823_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovPallets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TRANSACTIONINDEX', models.CharField(default='', max_length=16, unique=True)),
                ('PLANTID', models.CharField(default='', max_length=16)),
                ('WAREHOUSE', models.CharField(default='', max_length=16)),
                ('INTERNALSPECID', models.CharField(default='', max_length=16)),
                ('ORDERID', models.CharField(default='', max_length=16)),
                ('PARTID', models.CharField(default='', max_length=16)),
                ('OPERATIONNO', models.CharField(default='', max_length=16)),
                ('UNITTYPE', models.CharField(default='', max_length=16)),
                ('UNITNO', models.CharField(default='', max_length=16)),
                ('SOURCE', models.CharField(default='', max_length=16)),
                ('DESTINATION', models.CharField(default='', max_length=16)),
                ('EVENTDATETIME', models.DateTimeField(default=django.utils.timezone.now)),
                ('EVENTTIME', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='camion',
            name='dia',
            field=models.DateField(default=django.utils.timezone.now, max_length=10),
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2019, 8, 29, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fotocorrplan',
            name='fecha_foto',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2019, 8, 29, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='infowip',
            name='fechamuestra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_entrega',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2019, 8, 29, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proymkt',
            name='fechaproy',
            field=models.DateField(default=datetime.datetime(2019, 8, 29, 0, 0, tzinfo=utc)),
        ),
    ]
