# Generated by Django 2.0.13 on 2019-08-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0113_auto_20190830_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='movpallets',
            name='LOADID',
            field=models.CharField(default='0', max_length=16),
        ),
    ]
