# Generated by Django 2.0.13 on 2019-09-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0117_auto_20190901_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movpallets',
            name='PARTID',
            field=models.CharField(blank=True, default='0', max_length=16),
        ),
    ]
