# Generated by Django 2.0.13 on 2019-09-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0119_auto_20190901_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movpallets',
            name='DESTINATION',
            field=models.CharField(default='0', max_length=32),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='INTERNALSPECID',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
