# Generated by Django 2.0.13 on 2019-09-02 05:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0120_auto_20190901_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarja', models.CharField(default='0', max_length=8, unique=True)),
                ('padron', models.CharField(default='0', max_length=16)),
                ('fechaultmov', models.CharField(default='0', max_length=16)),
                ('fechacreac', models.CharField(default='0', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UbicPallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(default='vacio', max_length=8)),
                ('tipo', models.CharField(default='vacio', max_length=16)),
                ('m2tot', models.FloatField(default='0')),
                ('m2max', models.FloatField(default='0')),
                ('npallets', models.IntegerField(default='0')),
            ],
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2019, 9, 2, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2019, 9, 2, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2019, 9, 2, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proymkt',
            name='fechaproy',
            field=models.DateField(default=datetime.datetime(2019, 9, 2, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='pallet',
            name='ubic',
            field=models.ForeignKey(default='vacio', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ubic_pallet', to='blog.UbicPallet'),
        ),
    ]
