# Generated by Django 2.0.13 on 2019-09-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0121_auto_20190902_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicpallet',
            name='m2max',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ubicpallet',
            name='m2tot',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ubicpallet',
            name='npallets',
            field=models.IntegerField(default=0),
        ),
    ]
