# Generated by Django 2.0.13 on 2019-09-02 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0124_auto_20190902_0131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UbicPallet',
        ),
    ]
