# Generated by Django 2.0.13 on 2019-09-02 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0126_ubicpallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarja', models.CharField(default='0', max_length=8, unique=True)),
                ('padron', models.CharField(default='0', max_length=16)),
                ('fechaultmov', models.CharField(default='0', max_length=16)),
                ('fechacreac', models.CharField(default='0', max_length=16)),
                ('ubic', models.ForeignKey(default='vac', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ubic_pallet', to='blog.UbicPallet')),
            ],
        ),
    ]
