# Generated by Django 2.0.13 on 2019-09-02 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0129_auto_20190902_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='ubic',
            field=models.ForeignKey(default='vacio', on_delete=django.db.models.deletion.CASCADE, related_name='ubic', to='blog.UbicPallet'),
        ),
    ]
