# Generated by Django 2.0.13 on 2019-09-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0133_auto_20190902_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='ubic',
            field=models.CharField(default='vacio', max_length=32),
        ),
    ]
