# Generated by Django 2.0.13 on 2019-09-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0135_auto_20190903_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movpallets',
            name='ancho',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='largo',
            field=models.FloatField(default=0),
        ),
    ]
