# Generated by Django 2.0.13 on 2019-09-07 17:43

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0136_auto_20190904_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movpallets',
            old_name='ancho',
            new_name='kgpallet',
        ),
        migrations.RenameField(
            model_name='movpallets',
            old_name='largo',
            new_name='m2pallet',
        ),
        migrations.RenameField(
            model_name='movpallets',
            old_name='unidades',
            new_name='unidadespallet',
        ),
        migrations.RemoveField(
            model_name='movpallets',
            name='m2uni',
        ),
        migrations.RemoveField(
            model_name='movpallets',
            name='pesouni',
        ),
        migrations.AddField(
            model_name='pallet',
            name='alto',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pallet',
            name='ancho',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pallet',
            name='cliente',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AddField(
            model_name='pallet',
            name='kguni',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pallet',
            name='m2uni',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pallet',
            name='unidades',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2019, 9, 7, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2019, 9, 7, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2019, 9, 7, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='fechacreac',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='fechaultmov',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proymkt',
            name='fechaproy',
            field=models.DateField(default=datetime.datetime(2019, 9, 7, 0, 0, tzinfo=utc)),
        ),
    ]
