# Generated by Django 2.0.13 on 2019-09-08 00:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0140_remove_movpallets_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='kgpallet',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pallet',
            name='m2pallet',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2019, 9, 8, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2019, 9, 8, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2019, 9, 8, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proymkt',
            name='fechaproy',
            field=models.DateField(default=datetime.datetime(2019, 9, 8, 0, 0, tzinfo=utc)),
        ),
    ]
