# Generated by Django 2.0.13 on 2019-09-30 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0145_auto_20190930_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='ubic2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ubic_pallet', to='blog.UbicPallet'),
        ),
    ]
