# Generated by Django 2.0.13 on 2019-10-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0148_auto_20191007_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='tarja',
            field=models.CharField(default='0', max_length=9, unique=True),
        ),
    ]
