# Generated by Django 2.0.13 on 2019-10-09 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0152_auto_20191008_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palletcic',
            name='ancho',
        ),
    ]
