# Generated by Django 2.0.13 on 2019-10-31 20:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0157_auto_20191031_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 20, 28, 26, 190133, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 20, 28, 26, 190133, tzinfo=utc)),
        ),
    ]
