# Generated by Django 2.0.13 on 2019-11-04 04:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0158_auto_20191031_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoProgCorr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_foto', models.DateTimeField(default=django.utils.timezone.now, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IDProgCorr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=datetime.datetime(2019, 11, 4, 4, 15, 16, 149845, tzinfo=utc))),
                ('fecha_fin', models.DateTimeField(default=datetime.datetime(2019, 11, 4, 4, 15, 16, 149845, tzinfo=utc))),
                ('order_id', models.CharField(default='vacio', max_length=15)),
                ('ancho', models.IntegerField(default=0)),
                ('refile', models.IntegerField(default=0)),
                ('metrosL', models.IntegerField(default=0)),
                ('carton', models.CharField(default='vacio', max_length=15)),
                ('color', models.CharField(default='vacio', max_length=15)),
                ('programa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='foto_porgcorr', to='blog.FotoProgCorr')),
            ],
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2019, 11, 4, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2019, 11, 4, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 4, 15, 16, 150845, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 4, 15, 16, 150845, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2019, 11, 4, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proymkt',
            name='fechaproy',
            field=models.DateField(default=datetime.datetime(2019, 11, 4, 0, 0, tzinfo=utc)),
        ),
    ]
