# Generated by Django 2.0.13 on 2019-11-08 02:59

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0165_auto_20191107_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos_movpallets',
            old_name='fecha_fin',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='datos_movpallets',
            old_name='M2Conv',
            new_name='m2In',
        ),
        migrations.RenameField(
            model_name='datos_movpallets',
            old_name='M2Corr',
            new_name='m2Out',
        ),
        migrations.RenameField(
            model_name='datos_movpallets',
            old_name='M2Inv',
            new_name='m2Prod',
        ),
        migrations.RenameField(
            model_name='datos_proy_wip',
            old_name='m2In',
            new_name='M2Conv',
        ),
        migrations.RenameField(
            model_name='datos_proy_wip',
            old_name='m2Out',
            new_name='M2Corr',
        ),
        migrations.RenameField(
            model_name='datos_proy_wip',
            old_name='m2Prod',
            new_name='M2Inv',
        ),
        migrations.RenameField(
            model_name='datos_proy_wip',
            old_name='fecha',
            new_name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='datos_movpallets',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='datos_proy_wip',
            name='cantidadIn',
        ),
        migrations.RemoveField(
            model_name='datos_proy_wip',
            name='cantidadOut',
        ),
        migrations.RemoveField(
            model_name='datos_proy_wip',
            name='cantidadProd',
        ),
        migrations.AddField(
            model_name='datos_movpallets',
            name='cantidadIn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datos_movpallets',
            name='cantidadOut',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datos_movpallets',
            name='cantidadProd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datos_proy_wip',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 2, 59, 51, 170797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 2, 59, 51, 170797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 2, 59, 51, 171797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 2, 59, 51, 171797, tzinfo=utc)),
        ),
    ]
