# Generated by Django 2.0.13 on 2019-11-12 23:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0175_auto_20191111_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto_Calles_Inv_Cic_WIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(default='0', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Foto_Palletscti_Inv_Cic_WIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet', models.CharField(default='0', max_length=16)),
                ('ORDERID', models.CharField(default='0', max_length=16)),
                ('calle', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='foto_calle_wip1', to='blog.Foto_Calles_Inv_Cic_WIP')),
            ],
        ),
        migrations.CreateModel(
            name='Foto_Palletsencontrados_Inv_Cic_WIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet', models.CharField(default='0', max_length=16)),
                ('ORDERID', models.CharField(default='0', max_length=16)),
                ('calle', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='foto_calle_wip2', to='blog.Foto_Calles_Inv_Cic_WIP')),
            ],
        ),
        migrations.CreateModel(
            name='Foto_Palletsenotracalle_Inv_Cic_WIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet', models.CharField(default='0', max_length=16)),
                ('ORDERID', models.CharField(default='0', max_length=16)),
                ('calle', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='foto_calle_wip3', to='blog.Foto_Calles_Inv_Cic_WIP')),
            ],
        ),
        migrations.CreateModel(
            name='Foto_Palletsnoencontrados_Inv_Cic_WIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet', models.CharField(default='0', max_length=16)),
                ('ORDERID', models.CharField(default='0', max_length=16)),
                ('calle', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='foto_calle_wip4', to='blog.Foto_Calles_Inv_Cic_WIP')),
            ],
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2019, 11, 12, 0, 0)),
        ),
        migrations.AlterField(
            model_name='fotocorrplan',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 20, 42, 29, 655485), unique=True),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2019, 11, 12, 0, 0)),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 20, 42, 29, 653485)),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 20, 42, 29, 653485)),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='EVENTDATETIME',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 20, 42, 29, 649484)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 20, 42, 29, 655485)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 20, 42, 29, 655485)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2019, 11, 12, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proymkt',
            name='fechaproy',
            field=models.DateField(default=datetime.datetime(2019, 11, 12, 0, 0, tzinfo=utc)),
        ),
    ]
