# Generated by Django 2.0.13 on 2019-11-16 21:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0182_auto_20191115_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoRollos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RollID', models.CharField(default='0', max_length=16)),
                ('RollStandID', models.CharField(default='0', max_length=16)),
                ('formato', models.CharField(default='0', max_length=16)),
                ('peso', models.FloatField(default='0')),
                ('diametro', models.FloatField(default='0')),
                ('mlusados', models.FloatField(default='0')),
                ('mlrestantes', models.FloatField(default='0')),
                ('peelwaste', models.FloatField(default='0')),
                ('turno', models.CharField(default='0', max_length=16)),
                ('fechaini', models.DateTimeField(default=datetime.datetime(2019, 11, 16, 18, 49, 31, 746592))),
                ('idrollo', models.CharField(default='0', max_length=16)),
                ('origen', models.CharField(default='0', max_length=16)),
                ('destino', models.CharField(default='0', max_length=16)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2019, 11, 16, 18, 49, 31, 746592))),
                ('usuario', models.CharField(default='0', max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2019, 11, 16, 0, 0)),
        ),
        migrations.AlterField(
            model_name='foto_inv_cic_wip',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 18, 49, 31, 748592)),
        ),
        migrations.AlterField(
            model_name='fotocorrplan',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 18, 49, 31, 767593), unique=True),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2019, 11, 16, 0, 0)),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 18, 49, 31, 767593)),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 18, 49, 31, 767593)),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='EVENTDATETIME',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 18, 49, 31, 764593)),
        ),
        migrations.AlterField(
            model_name='movrollos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 18, 49, 31, 747592)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 18, 49, 31, 768593)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 18, 49, 31, 768593)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2019, 11, 16, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proymkt',
            name='fechaproy',
            field=models.DateField(default=datetime.datetime(2019, 11, 16, 0, 0, tzinfo=utc)),
        ),
    ]
