# Generated by Django 2.0.13 on 2020-04-08 15:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0225_auto_20200406_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprog',
            name='m2despachados',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detalleprog',
            name='m2ingresados_bpt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detalleprog',
            name='m2producidos',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detalleprog',
            name='unidades_despachadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detalleprog',
            name='unidades_ingresadas_bpt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detalleprog',
            name='unidades_producidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alertabot',
            name='fechaalerta',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 51, 995785)),
        ),
        migrations.AlterField(
            model_name='alertabot',
            name='fechaevento',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 51, 996785)),
        ),
        migrations.AlterField(
            model_name='camion',
            name='dia',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 41788), max_length=10),
        ),
        migrations.AlterField(
            model_name='consumorollos',
            name='fechaini',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 51, 997785)),
        ),
        migrations.AlterField(
            model_name='datos_kpi_diario',
            name='dia',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 0, 0)),
        ),
        migrations.AlterField(
            model_name='datos_movpallets',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 5786)),
        ),
        migrations.AlterField(
            model_name='datos_movpallets',
            name='fechafin',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 5786)),
        ),
        migrations.AlterField(
            model_name='datos_movpallets',
            name='programa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='foto_datosmovpallet', to='blog.Foto_Datos_MovPallets'),
        ),
        migrations.AlterField(
            model_name='datos_movpallets_b',
            name='fechafin',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 6786)),
        ),
        migrations.AlterField(
            model_name='datos_movpallets_b',
            name='fechaini',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 6786)),
        ),
        migrations.AlterField(
            model_name='datos_movpallets_b',
            name='programa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='foto_datosmovpalletB', to='blog.Foto_Datos_MovPallets'),
        ),
        migrations.AlterField(
            model_name='datos_movpallets_c',
            name='programa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='foto_datosmovpalletC', to='blog.Foto_Datos_MovPallets'),
        ),
        migrations.AlterField(
            model_name='datos_proy_wip',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 13786)),
        ),
        migrations.AlterField(
            model_name='datos_proy_wip',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 13786)),
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 0, 0)),
        ),
        migrations.AlterField(
            model_name='foto_consumorollos',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 51, 996785)),
        ),
        migrations.AlterField(
            model_name='foto_datos_inv_wip',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 2786), unique=True),
        ),
        migrations.AlterField(
            model_name='foto_datos_movpallets',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 5786), unique=True),
        ),
        migrations.AlterField(
            model_name='foto_inv_cic_wip',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 51, 998785)),
        ),
        migrations.AlterField(
            model_name='foto_kpi',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 9786), unique=True),
        ),
        migrations.AlterField(
            model_name='fotocorrplan',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 27787), unique=True),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 0, 0)),
        ),
        migrations.AlterField(
            model_name='fotoprogcorr',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 25787), unique=True),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 26787)),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 26787)),
        ),
        migrations.AlterField(
            model_name='infowip',
            name='fechamuestra',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 43788)),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='EVENTDATETIME',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 20787)),
        ),
        migrations.AlterField(
            model_name='movrollos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 51, 998785)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 27787)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 27787)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 0, 0)),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='fechacamion',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 17787)),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='fechacreac',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 17787)),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='fechapll',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 17787)),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='fechaultmov',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 17787)),
        ),
        migrations.AlterField(
            model_name='palletcic',
            name='fechatoma',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 16786)),
        ),
        migrations.AlterField(
            model_name='proymkt',
            name='fechaproy',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 0, 0)),
        ),
        migrations.AlterField(
            model_name='tomainvcic',
            name='fechatomainvcic',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 53, 52, 15786)),
        ),
    ]
