# Generated by Django 2.0.5 on 2018-10-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181013_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodreal',
            name='datefinajustada',
            field=models.DateTimeField(),
        ),
    ]
