# Generated by Django 2.0.5 on 2018-10-16 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181016_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 10, 16, 0, 46, 6, 420678)),
        ),
    ]
