# Generated by Django 2.0.5 on 2018-10-16 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181016_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 10, 16, 0, 55, 23, 515542)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='obs',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='texto',
            field=models.TextField(default=''),
        ),
    ]
