# Generated by Django 2.0.5 on 2018-10-16 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20181016_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 10, 16, 0, 58, 33, 457406)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='obs',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
