# Generated by Django 2.0.5 on 2018-10-16 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20181016_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 10, 16, 1, 0, 44, 882923)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='obs',
            field=models.CharField(default='S/N', max_length=100),
        ),
    ]
