# Generated by Django 2.0.5 on 2018-10-22 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20181016_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Padron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padron', models.CharField(default='.', editable=False, max_length=100, unique=True)),
                ('m2uni', models.FloatField(default=0)),
                ('uxg', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 10, 21, 23, 48, 10, 157674)),
        ),
    ]
