# Generated by Django 2.0.5 on 2018-10-22 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20181021_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='padron',
            name='status',
            field=models.CharField(default='.', max_length=100),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 10, 22, 0, 18, 19, 889185)),
        ),
    ]
