# Generated by Django 2.0.5 on 2018-10-27 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20181022_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaConv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaajust', models.DateField(default=datetime.datetime(2018, 10, 27, 0, 0))),
                ('turno', models.CharField(default='vacio', max_length=10)),
                ('maquina', models.CharField(default='vacio', max_length=10)),
                ('compId', models.FloatField(default=0)),
                ('compM2', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 10, 27, 19, 57, 45, 774612)),
        ),
    ]
