# Generated by Django 2.0.5 on 2018-10-27 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20181027_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinas',
            name='maquina',
            field=models.CharField(default='vacio', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 10, 27, 20, 2, 12, 908892)),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='turno',
            field=models.CharField(default='vacio', max_length=10, unique=True),
        ),
    ]
