# Generated by Django 2.0.5 on 2018-11-02 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20181027_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenprog',
            name='turnohorfin',
            field=models.CharField(default='vacio', max_length=20),
        ),
        migrations.AddField(
            model_name='ordenprog',
            name='turnohorini',
            field=models.CharField(default='vacio', max_length=20),
        ),
        migrations.AlterField(
            model_name='diaconv',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2018, 11, 2, 0, 0)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 11, 2, 13, 55, 41, 331022)),
        ),
    ]
