# Generated by Django 2.0.5 on 2018-11-11 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20181103_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaconv',
            name='maquina',
        ),
        migrations.RemoveField(
            model_name='diaconv',
            name='turno',
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2018, 11, 11, 0, 0)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 11, 11, 10, 24, 53, 652147)),
        ),
        migrations.DeleteModel(
            name='DiaConv',
        ),
    ]
