# Generated by Django 2.0.5 on 2018-11-13 12:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20181111_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProgCorr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajuste', models.CharField(default='vacio', max_length=20)),
                ('onda', models.CharField(default='vacio', max_length=20)),
                ('formato', models.CharField(default='vacio', max_length=20)),
                ('carton', models.CharField(default='vacio', max_length=20)),
                ('metroslineales', models.IntegerField(default=0)),
                ('trim', models.IntegerField(default=0)),
                ('papeles', models.CharField(default='vacio', max_length=50)),
                ('datosinferior', models.CharField(default='vacio', max_length=200)),
                ('datefin', models.DateTimeField()),
                ('datefinajustada', models.DateTimeField()),
                ('turno', models.CharField(default='vacio', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProgCorr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programa', models.DateTimeField()),
                ('horizonteini', models.DateTimeField(blank=True)),
                ('turnohorini', models.CharField(default='vacio', max_length=20)),
                ('horizontefin', models.DateTimeField(blank=True)),
                ('turnohorfin', models.CharField(default='vacio', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='diaconv2',
            name='prod2IdDRO',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diaconv2',
            name='prod2IdFFG',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diaconv2',
            name='prod2IdFFW',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diaconv2',
            name='prod2IdHCR',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diaconv2',
            name='prod2IdTCY',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diaconv2',
            name='prod2IdWRD',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diaconv2',
            name='prod2M2DRO',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diaconv2',
            name='prod2M2FFG',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diaconv2',
            name='prod2M2FFW',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diaconv2',
            name='prod2M2HCR',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diaconv2',
            name='prod2M2TCY',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diaconv2',
            name='prod2M2WRD',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2018, 11, 13, 0, 0)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 11, 13, 9, 50, 17, 288076)),
        ),
        migrations.AddField(
            model_name='detalleprogcorr',
            name='programma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fecha_prog', to='blog.OrdenProgCorr'),
        ),
    ]
