# Generated by Django 2.0.5 on 2018-11-13 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20181113_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='SO',
            field=models.CharField(default='.', max_length=100),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 11, 13, 11, 4, 34, 482110)),
        ),
    ]
