# Generated by Django 2.0.5 on 2018-11-17 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20181113_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='SOPosition',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2018, 11, 17, 0, 0)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 11, 17, 14, 9, 37, 190799)),
        ),
    ]
