# Generated by Django 2.0.5 on 2018-11-18 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20181117_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2018, 11, 18, 0, 0)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 11, 18, 16, 24, 58, 401445)),
        ),
        migrations.AlterField(
            model_name='prodreal',
            name='qOrd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prodreal',
            name='qProd',
            field=models.IntegerField(default=0),
        ),
    ]
