# Generated by Django 2.0.5 on 2018-11-18 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20181118_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='blanksrequired',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='blankstocorr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='qOrd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 11, 18, 19, 20, 41, 634484)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='SOPosition',
            field=models.IntegerField(default=0),
        ),
    ]
