# Generated by Django 2.0.5 on 2018-11-22 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20181122_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaconv2',
            name='anno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diaconv2',
            name='mes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diaconv2',
            name='semana',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 11, 22, 20, 6, 17, 181811)),
        ),
    ]
