# Generated by Django 2.0.5 on 2018-11-25 03:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_auto_20181122_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='clave',
            field=models.CharField(default='.', max_length=100),
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2018, 11, 25, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 11, 25, 3, 30, 45, 598619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2018, 11, 25, 0, 0, tzinfo=utc)),
        ),
    ]
