# Generated by Django 2.0.5 on 2018-12-09 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_auto_20181208_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotoinventario',
            old_name='CPP_3_meses',
            new_name='CPP_3_meses_kg',
        ),
        migrations.RenameField(
            model_name='fotoinventario',
            old_name='CPP_6_meses',
            new_name='CPP_6_meses_kg',
        ),
        migrations.RenameField(
            model_name='fotoinventario',
            old_name='blanco_3_meses',
            new_name='blanco_3_meses_kg',
        ),
        migrations.RenameField(
            model_name='fotoinventario',
            old_name='blanco_6_meses',
            new_name='blanco_6_meses_kg',
        ),
        migrations.RenameField(
            model_name='fotoinventario',
            old_name='kraft_3_meses',
            new_name='kraft_3_meses_kg',
        ),
        migrations.RenameField(
            model_name='fotoinventario',
            old_name='kraft_6_meses',
            new_name='kraft_6_meses_kg',
        ),
        migrations.RenameField(
            model_name='fotoinventario',
            old_name='otros_3_meses',
            new_name='otros_3_meses_kg',
        ),
        migrations.RenameField(
            model_name='fotoinventario',
            old_name='otros_6_meses',
            new_name='otros_6_meses_kg',
        ),
        migrations.RenameField(
            model_name='fotoinventario',
            old_name='total_CPP',
            new_name='total_CPP_kg',
        ),
        migrations.RenameField(
            model_name='fotoinventario',
            old_name='total_blanco',
            new_name='total_blanco_kg',
        ),
        migrations.RenameField(
            model_name='fotoinventario',
            old_name='total_kraft',
            new_name='total_kraft_kg',
        ),
        migrations.RenameField(
            model_name='fotoinventario',
            old_name='total_otros',
            new_name='total_otros_kg',
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 12, 9, 12, 42, 22, 445169, tzinfo=utc)),
        ),
    ]
