# Generated by Django 2.0.5 on 2018-12-10 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_auto_20181209_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoinventario',
            name='CPP_1_meses_kg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fotoinventario',
            name='blanco_1_meses_kg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fotoinventario',
            name='kraft_1_meses_kg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fotoinventario',
            name='otros_1_meses_kg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2018, 12, 10, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2018, 12, 10, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2018, 12, 10, 17, 47, 31, 878780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2018, 12, 10, 0, 0, tzinfo=utc)),
        ),
    ]
