# Generated by Django 2.0.13 on 2019-04-28 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0059_auto_20190210_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoWIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador', models.IntegerField(default=0)),
                ('M2FFG', models.FloatField(default=0)),
                ('PiFFG', models.FloatField(default=0)),
                ('M2FFW', models.FloatField(default=0)),
                ('PiFFW', models.FloatField(default=0)),
                ('M2TCY', models.FloatField(default=0)),
                ('PiTCY', models.FloatField(default=0)),
                ('M2DRO', models.FloatField(default=0)),
                ('PiDRO', models.FloatField(default=0)),
                ('M2WRD', models.FloatField(default=0)),
                ('PiWRD', models.FloatField(default=0)),
                ('M2HCR', models.FloatField(default=0)),
                ('PiHCR', models.FloatField(default=0)),
                ('M2Otros', models.FloatField(default=0)),
                ('PiOtros', models.FloatField(default=0)),
                ('M2Total', models.FloatField(default=0)),
                ('PiTotal', models.FloatField(default=0)),
                ('fechamuestra', models.DateField(default=datetime.datetime(2019, 4, 28, 0, 0, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 17, 30, 46, 274888, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proymkt',
            name='fechaproy',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 0, 0, tzinfo=utc)),
        ),
    ]
