# Generated by Django 2.2.2 on 2019-07-02 02:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0073_auto_20190702_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infowip',
            name='fechamuestra',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 2, 2, 42, 49, 59437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 7, 2, 2, 42, 49, 64720, tzinfo=utc)),
        ),
    ]
