# Generated by Django 2.2.2 on 2019-07-16 15:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0091_auto_20190716_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencorrplan',
            name='maquina',
            field=models.CharField(default='vacio', max_length=5),
        ),
        migrations.AlterField(
            model_name='camion',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 7, 16, 15, 29, 20, 345099, tzinfo=utc), max_length=10),
        ),
        migrations.AlterField(
            model_name='fotocorrplan',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 16, 15, 29, 20, 343094, tzinfo=utc), unique=True),
        ),
        migrations.AlterField(
            model_name='infowip',
            name='fechamuestra',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 16, 15, 29, 20, 345805, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='dia',
            field=models.DateField(default=datetime.datetime(2019, 7, 16, 15, 29, 20, 351097, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='area',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='cant_corr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='cant_ord',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='carton',
            field=models.CharField(default='vacio', max_length=6),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='comprometida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='padron',
            field=models.CharField(default='vacio', max_length=20),
        ),
    ]
