# Generated by Django 2.0.13 on 2019-08-30 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0109_auto_20190829_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2019, 8, 30, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2019, 8, 30, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='DESTINATION',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='EVENTTIME',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='INTERNALSPECID',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='OPERATIONNO',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='ORDERID',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='PARTID',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='PLANTID',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='SOURCE',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='TRANSACTIONINDEX',
            field=models.CharField(default='0', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='UNITNO',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='UNITTYPE',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='WAREHOUSE',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2019, 8, 30, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proymkt',
            name='fechaproy',
            field=models.DateField(default=datetime.datetime(2019, 8, 30, 0, 0, tzinfo=utc)),
        ),
    ]
