# Generated by Django 2.0.13 on 2019-08-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0110_auto_20190830_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movpallets',
            name='TRANSACTIONINDEX',
            field=models.CharField(default='0', max_length=16),
        ),
    ]
