# Generated by Django 2.0.13 on 2019-08-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0111_auto_20190830_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movpallets',
            name='EVENTDATETIME',
            field=models.CharField(default='0', max_length=16),
        ),
    ]
