# Generated by Django 2.0.13 on 2019-09-01 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0115_auto_20190901_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movpallets',
            name='EVENTDATETIME',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
