# Generated by Django 2.0.13 on 2019-09-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0118_auto_20190901_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movpallets',
            name='SOURCE',
            field=models.CharField(blank=True, default='0', max_length=32),
        ),
    ]
