# Generated by Django 2.0.13 on 2019-09-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0125_delete_ubicpallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicPallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(default='vacio', max_length=8)),
                ('tipo', models.CharField(default='vacio', max_length=16)),
                ('m2tot', models.FloatField(default=0)),
                ('m2max', models.FloatField(default=0)),
                ('npallets', models.IntegerField(default=0)),
            ],
        ),
    ]
