# Generated by Django 2.0.13 on 2019-09-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0127_pallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicpallet',
            name='calle',
            field=models.CharField(default='vacio', max_length=32),
        ),
    ]
