# Generated by Django 2.0.13 on 2019-09-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0137_auto_20190907_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='movpallets',
            name='alto',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movpallets',
            name='ancho',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movpallets',
            name='cliente',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AddField(
            model_name='movpallets',
            name='kguni',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movpallets',
            name='m2uni',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movpallets',
            name='ubic',
            field=models.CharField(default='vacio', max_length=32),
        ),
        migrations.AddField(
            model_name='movpallets',
            name='unidades',
            field=models.FloatField(default=0),
        ),
    ]
