# Generated by Django 2.0.13 on 2019-09-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0143_auto_20190910_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobinvcic',
            name='nbobina',
            field=models.CharField(default='', max_length=16),
        ),
    ]
