# Generated by Django 2.0.13 on 2019-09-30 23:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0144_auto_20190910_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='ubic2',
            field=models.ForeignKey(default='312', on_delete=django.db.models.deletion.CASCADE, related_name='ubic_pallet', to='blog.UbicPallet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2019, 9, 30, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2019, 9, 30, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2019, 9, 30, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proymkt',
            name='fechaproy',
            field=models.DateField(default=datetime.datetime(2019, 9, 30, 0, 0, tzinfo=utc)),
        ),
    ]
