# Generated by Django 2.0.13 on 2019-10-08 22:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0149_auto_20191007_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalletCic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarja', models.CharField(default='0', max_length=9, unique=True)),
                ('ancho', models.FloatField(default=0)),
                ('ubic', models.CharField(default='vacio', max_length=32)),
                ('fechatoma', models.DateTimeField(default=django.utils.timezone.now)),
                ('ubic2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ubic_pallet_cic', to='blog.UbicPallet')),
            ],
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2019, 10, 8, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2019, 10, 8, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2019, 10, 8, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proymkt',
            name='fechaproy',
            field=models.DateField(default=datetime.datetime(2019, 10, 8, 0, 0, tzinfo=utc)),
        ),
    ]
