# Generated by Django 2.0.13 on 2019-10-31 20:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0156_auto_20191031_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datoswip_prog',
            old_name='m224h',
            new_name='m2Prog24h',
        ),
        migrations.RenameField(
            model_name='datoswip_prog',
            old_name='m2EnInv',
            new_name='m2inv',
        ),
        migrations.RenameField(
            model_name='datoswip_prog',
            old_name='m2Prog24',
            new_name='m2inv24h',
        ),
        migrations.AlterField(
            model_name='datoswip_prog',
            name='maquina',
            field=models.CharField(default='0', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 20, 28, 13, 815425, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 20, 28, 13, 815425, tzinfo=utc)),
        ),
    ]
