# Generated by Django 2.0.13 on 2019-11-07 23:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0163_auto_20191107_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos_proy_wip',
            old_name='fecha',
            new_name='fecha_fin',
        ),
        migrations.AddField(
            model_name='datos_proy_wip',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 23, 25, 52, 851487, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 23, 25, 52, 851487, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 23, 25, 52, 853487, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 23, 25, 52, 853487, tzinfo=utc)),
        ),
    ]
