# Generated by Django 2.0.13 on 2019-11-09 14:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0166_auto_20191107_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Inv_WIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(default='0', max_length=16)),
                ('cuenta', models.IntegerField(default=0)),
                ('m2tot', models.FloatField(default=0)),
                ('indice', models.IntegerField(default=0)),
                ('dias', models.IntegerField(default=0)),
                ('al1', models.IntegerField(default=0)),
                ('al2', models.IntegerField(default=0)),
                ('al3', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Foto_Datos_Inv_WIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_foto', models.DateTimeField(default=django.utils.timezone.now, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='diaconv2',
            name='diaajust',
            field=models.DateField(default=datetime.datetime(2019, 11, 9, 0, 0)),
        ),
        migrations.AlterField(
            model_name='fotocorrplan',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 11, 52, 57, 490998), unique=True),
        ),
        migrations.AlterField(
            model_name='fotoinventario',
            name='fecha_carga',
            field=models.DateField(default=datetime.datetime(2019, 11, 9, 0, 0)),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 11, 52, 57, 489998)),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 11, 52, 57, 489998)),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='EVENTDATETIME',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 11, 52, 57, 487998)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 11, 52, 57, 490998)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 11, 52, 57, 490998)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='fechacarga',
            field=models.DateField(default=datetime.datetime(2019, 11, 9, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proymkt',
            name='fechaproy',
            field=models.DateField(default=datetime.datetime(2019, 11, 9, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='datos_inv_wip',
            name='programa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='foto_datosinvwip', to='blog.Foto_Datos_Inv_WIP'),
        ),
    ]
