# Generated by Django 2.0.13 on 2019-11-09 20:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0167_auto_20191109_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroEntradaWIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOADID', models.CharField(default='0', max_length=16)),
                ('ORDERID', models.CharField(default='0', max_length=16)),
                ('DESTINATION', models.CharField(default='0', max_length=32)),
                ('EVENTDATETIME', models.DateTimeField(default=datetime.datetime(2019, 11, 9, 17, 47, 48, 654602))),
                ('programa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='foto_datosinvwip1', to='blog.Foto_Datos_Inv_WIP')),
            ],
        ),
        migrations.CreateModel(
            name='FiltroSalidaWIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOADID', models.CharField(default='0', max_length=16)),
                ('ORDERID', models.CharField(default='0', max_length=16)),
                ('DESTINATION', models.CharField(default='0', max_length=32)),
                ('EVENTDATETIME', models.DateTimeField(default=datetime.datetime(2019, 11, 9, 17, 47, 48, 654602))),
                ('programa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='foto_datosinvwip2', to='blog.Foto_Datos_Inv_WIP')),
            ],
        ),
        migrations.AlterField(
            model_name='fotocorrplan',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 17, 47, 48, 664602), unique=True),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 17, 47, 48, 663602)),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 17, 47, 48, 663602)),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='EVENTDATETIME',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 17, 47, 48, 661602)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 17, 47, 48, 664602)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 17, 47, 48, 664602)),
        ),
    ]
