# Generated by Django 2.0.13 on 2019-11-10 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0170_auto_20191110_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_movpallets',
            name='m2Conv',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='datos_movpallets',
            name='m2Corr',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fotocorrplan',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 1, 50, 4, 866305), unique=True),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 1, 50, 4, 865305)),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 1, 50, 4, 865305)),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='EVENTDATETIME',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 1, 50, 4, 863305)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 1, 50, 4, 866305)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 1, 50, 4, 866305)),
        ),
    ]
