# Generated by Django 2.0.13 on 2019-11-10 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0171_auto_20191110_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='idprogcorr',
            name='UPID',
            field=models.CharField(default='vacio', max_length=15),
        ),
        migrations.AddField(
            model_name='idprogcorr',
            name='UPID_areaplaca',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='idprogcorr',
            name='UPID_areatot',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='idprogcorr',
            name='UPID_nplacas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idprogcorr',
            name='UPLD',
            field=models.CharField(default='vacio', max_length=15),
        ),
        migrations.AddField(
            model_name='idprogcorr',
            name='UPLD_areaplaca',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='idprogcorr',
            name='UPLD_areatot',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='idprogcorr',
            name='UPLD_nplacas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fotocorrplan',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 17, 40, 43, 232215), unique=True),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 17, 40, 43, 231215)),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 17, 40, 43, 231215)),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='EVENTDATETIME',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 17, 40, 43, 229215)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 17, 40, 43, 233215)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 17, 40, 43, 233215)),
        ),
    ]
