# Generated by Django 2.0.13 on 2019-11-10 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0172_auto_20191110_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idprogcorr',
            old_name='UPID',
            new_name='LKID',
        ),
        migrations.RenameField(
            model_name='idprogcorr',
            old_name='UPID_areaplaca',
            new_name='LKID_areaplaca',
        ),
        migrations.RenameField(
            model_name='idprogcorr',
            old_name='UPID_areatot',
            new_name='LKID_areatot',
        ),
        migrations.RenameField(
            model_name='idprogcorr',
            old_name='UPID_nplacas',
            new_name='LKID_nplacas',
        ),
        migrations.RenameField(
            model_name='idprogcorr',
            old_name='UPLD',
            new_name='UKID',
        ),
        migrations.RenameField(
            model_name='idprogcorr',
            old_name='UPLD_areaplaca',
            new_name='UKID_areaplaca',
        ),
        migrations.RenameField(
            model_name='idprogcorr',
            old_name='UPLD_areatot',
            new_name='UKID_areatot',
        ),
        migrations.RenameField(
            model_name='idprogcorr',
            old_name='UPLD_nplacas',
            new_name='UKID_nplacas',
        ),
        migrations.AlterField(
            model_name='fotocorrplan',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 19, 51, 57, 449034), unique=True),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 19, 51, 57, 448034)),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 19, 51, 57, 448034)),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='EVENTDATETIME',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 19, 51, 57, 446034)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 19, 51, 57, 450034)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 19, 51, 57, 450034)),
        ),
    ]
