# Generated by Django 2.0.13 on 2019-11-16 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0183_auto_20191116_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumorollos',
            old_name='destino',
            new_name='grado',
        ),
        migrations.RemoveField(
            model_name='consumorollos',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='consumorollos',
            name='idrollo',
        ),
        migrations.RemoveField(
            model_name='consumorollos',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='consumorollos',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='consumorollos',
            name='fechaini',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 19, 8, 23, 198307)),
        ),
        migrations.AlterField(
            model_name='foto_inv_cic_wip',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 19, 8, 23, 200307)),
        ),
        migrations.AlterField(
            model_name='fotocorrplan',
            name='fecha_foto',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 19, 8, 23, 214308), unique=True),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 19, 8, 23, 212308)),
        ),
        migrations.AlterField(
            model_name='idprogcorr',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 19, 8, 23, 212308)),
        ),
        migrations.AlterField(
            model_name='movpallets',
            name='EVENTDATETIME',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 19, 8, 23, 210308)),
        ),
        migrations.AlterField(
            model_name='movrollos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 19, 8, 23, 198307)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 19, 8, 23, 215308)),
        ),
        migrations.AlterField(
            model_name='ordencorrplan',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 19, 8, 23, 215308)),
        ),
    ]
